---
title: The Digital Abode of Ion Lights
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  builds:
    title: Projects
    output: true
    permalink: builds/:path
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: builds
  values:
    layout: builds
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:categories/:year/:title"
heading: Ion Lights
email: john@ionlights.com
description: 
baseurl: ''
url: http://ionlights.com
social:
  github:
    uname: ionlights
    icon: github
  twitter:
    uname: ionlights
    icon: twitter
  dribbble:
    uname: ionlights
    icon: dribbble
  linkedin:
    uname: in/ionlights
    icon: linkedin
markdown: kramdown
